### ISSUE TITLE
Newly added mobj are set not to appear in Time Attack mode by default

### ISSUE THREAD

**Issue by SuperGameCube** [HaroohiePals/MarioKartToolbox#7]
When an object is first added into a course through the NKM Editor, it is set not to appear in Time Attack mode by default.
This behavior was originally suggested so that Item Boxes would not appear in Time Attack mode by mistake.
However, this has led to more troublesome problem where objects that should appear in Time Attack mode are set not to by mistake.
This behavior also serves as a redundant solution considering that Item Boxes that appear in Time Attack mode are reported in the Error List.

**Comment by Ermelber** [comment]
I have a suggestion, maybe adding a map object through the add button or draw tool should copy the settings from the last selected object, at least the object ID and TT visibility flag.

**Comment by SuperGameCube** [comment]
I feel that could be expanded into something better, like being able to provide information to the draw tool about what's being placed beforehand. For example, if you're placing EPOI you could set it to place EPOI with a specified point size.
