### ISSUE TITLE
Keybind overlap issue/Scale tool bug

### ISSUE THREAD

**Issue by Jacanapes** [HaroohiePals/MarioKartToolbox#9]
Presently, the Scale tool shortcut (S) overlaps with the basic movement keys (WASD) in the 3D editor. It is very easy to accidentally hit S while trying to move the camera, which can often result in objects being unintentionally scaled without notice as there is currently no obvious visualization of an object's scale in the 3D editor (many objects are still represented as fixed cubes). Perhaps rebinding the tool shortcuts to also require Shift to be held down would remedy this. 

Additionally, there is a legitimate bug present. The scale tool will still be active while moving the camera which you can see occur in the attached gif:

![moving-ezgif com-resize](https://github.com/HaroohiePals/MarioKartToolbox/assets/50172084/1d4bc3a0-88ac-48f2-a5b0-556c91f5aebc)

**Comment by SuperGameCube** [comment]
Currently, Shift is used while moving to increase movement speed, so that would need to be taken into consideration.

**Comment by Ermelber** [comment]
> Currently, Shift is used while moving to increase movement speed, so that would need to be taken into consideration.

It is true, however that movement speed increase is only applied when you move the camera when you drag right click (as a matter of fact, WASD movement only work if you right click), meaning that this specific key can overlap without problems. 

I think the main issue is that it's too easy to misinput S before you move the camera, triggering the scale tool and causing that issue shown above.

**Comment by SuperGameCube** [comment]
If you hold Shift to speed up the camera and press S right before holding the right mouse button, you'd still unintentionally activate the scale tool

**Comment by Ermelber** [comment]
This will be addressed by cancelling all gizmo operations when you right click
